name: Deploy to Preprod

on:
  push:
    branches: [preprod]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Ionos Preprod
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.IONOS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.IONOS_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy to server
        run: |
          ssh ${{ secrets.IONOS_USER }}@${{ secrets.IONOS_HOST }} << 'EOF'
            set -e
            
            # Navigate to project directory
            cd ~/projects/test/vulcain
            
            # Pull latest changes (safe even if already on preprod branch)
            git fetch origin
            git checkout preprod || git checkout -b preprod origin/preprod
            git pull origin preprod
            
            # Deploy with Docker
            make down || true
            make upb
            
            # Verify deployment
            sleep 10
            make logs-app --no-print-directory | head -20
            
          EOF
          
      - name: Verify deployment
        run: |
          # Test if services are responding
          ssh ${{ secrets.IONOS_USER }}@${{ secrets.IONOS_HOST }} << 'EOF'
            curl -f https://vulcain.woopear.fr/health || echo "Frontend health check failed"
            curl -f https://vulcain-api.woopear.fr/health || echo "API health check failed"
          EOF